### ISSUE TITLE
Unknown struct/union: 'uint64'

### ISSUE THREAD

**Issue by aravindhsampath** [FrauBSD/nfsiosnoop#1]
Hello.

I tried to run nfsiosnoop on our CentOS 8 NFS server, and ended up with the following.

```
# nfsiosnoop
INFO Tracing I/O... Hit Ctrl-C to end.
INFO Gathering open file-descriptor info...
Unknown struct/union: 'uint64'
Unknown struct/union: 'uint64'
Unknown struct/union: 'int64'
Unknown struct/union: 'int64'
Unknown struct/union: 'int64'
Unknown struct/union: 'int64'
Unknown struct/union: 'int64'
Unknown struct/union: 'int64'
Unknown struct/union: 'int64'
```

Do you have any clue what might be going on here?

**Comment by freebsdfrau** [comment]
It looks like CentOS 8.1 ships with an older software than what is required. I am currently working on a script to update CentOS 8 to the required minimum versions

**Comment by freebsdfrau** [comment]
OK. Run these steps on CentOS 8.1:

```
git clone https://github.com/FrauBSD/el8-bpf-specs.git
cd el8-bpf-specs
./build-all.sh
```

Repo Link: [FrauBSD.org/el8-bpf-specs](https://FrauBSD.org/el8-bpf-specs)

That should update:
1. `bcc` from version 0.8.0-4 to 0.11.0-1
2. `bpftrace` from version 0.9-3 to 0.9.3-1

It will produce `bcc` and `bpftrace` RPMs in `~/rpmbuild/RPMS/` for you to deploy on similar systems (for example, by tossing them into an internal yum repository or installing manually with `rpm -ivh <file>`).

**Comment by aravindhsampath** [comment]
Thanks for this. I now have updated versions of bcc, bpftrace and got nfsiosnoop working!
